##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Apr 16 09:33:21 2015
##  Generated by MIG Version 2.3
##  
##################################################################################################
##  File name :       mig_7series_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690T-FFG1761
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         800 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8KTF51264HZ-1G9
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################

#create_clock -period 5 [get_ports sys_clk_i]
#set_propagated_clock sys_clk_i

############## NET - IOSTANDARD ##################

proc annotateDDRWires0 { pathPrefix } { 
    # PadFunction: IO_L23N_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[0]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[0]"]
    set_property PACKAGE_PIN N14 [get_ports "${pathPrefix}_dq[0]"]

    # PadFunction: IO_L22P_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[1]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[1]"]
    set_property PACKAGE_PIN N13 [get_ports "${pathPrefix}_dq[1]"]

    # PadFunction: IO_L20N_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[2]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[2]"]
    set_property PACKAGE_PIN L14 [get_ports "${pathPrefix}_dq[2]"]

    # PadFunction: IO_L20P_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[3]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[3]"]
    set_property PACKAGE_PIN M14 [get_ports "${pathPrefix}_dq[3]"]

    # PadFunction: IO_L24P_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[4]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[4]"]
    set_property PACKAGE_PIN M12 [get_ports "${pathPrefix}_dq[4]"]

    # PadFunction: IO_L23P_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[5]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[5]"]
    set_property PACKAGE_PIN N15 [get_ports "${pathPrefix}_dq[5]"]

    # PadFunction: IO_L24N_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[6]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[6]"]
    set_property PACKAGE_PIN M11 [get_ports "${pathPrefix}_dq[6]"]

    # PadFunction: IO_L19P_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[7]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[7]"]
    set_property PACKAGE_PIN L12 [get_ports "${pathPrefix}_dq[7]"]

    # PadFunction: IO_L17P_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[8]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[8]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[8]"]
    set_property PACKAGE_PIN K14 [get_ports "${pathPrefix}_dq[8]"]

    # PadFunction: IO_L17N_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[9]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[9]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[9]"]
    set_property PACKAGE_PIN K13 [get_ports "${pathPrefix}_dq[9]"]

    # PadFunction: IO_L14N_T2_SRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[10]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[10]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[10]"]
    set_property PACKAGE_PIN H13 [get_ports "${pathPrefix}_dq[10]"]

    # PadFunction: IO_L14P_T2_SRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[11]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[11]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[11]"]
    set_property PACKAGE_PIN J13 [get_ports "${pathPrefix}_dq[11]"]

    # PadFunction: IO_L18P_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[12]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[12]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[12]"]
    set_property PACKAGE_PIN L16 [get_ports "${pathPrefix}_dq[12]"]

    # PadFunction: IO_L18N_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[13]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[13]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[13]"]
    set_property PACKAGE_PIN L15 [get_ports "${pathPrefix}_dq[13]"]

    # PadFunction: IO_L13N_T2_MRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[14]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[14]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[14]"]
    set_property PACKAGE_PIN H14 [get_ports "${pathPrefix}_dq[14]"]

    # PadFunction: IO_L16N_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[15]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[15]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[15]"]
    set_property PACKAGE_PIN J15 [get_ports "${pathPrefix}_dq[15]"]

    # PadFunction: IO_L7N_T1_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[16]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[16]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[16]"]
    set_property PACKAGE_PIN E15 [get_ports "${pathPrefix}_dq[16]"]

    # PadFunction: IO_L8N_T1_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[17]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[17]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[17]"]
    set_property PACKAGE_PIN E13 [get_ports "${pathPrefix}_dq[17]"]

    # PadFunction: IO_L11P_T1_SRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[18]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[18]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[18]"]
    set_property PACKAGE_PIN F15 [get_ports "${pathPrefix}_dq[18]"]

    # PadFunction: IO_L8P_T1_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[19]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[19]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[19]"]
    set_property PACKAGE_PIN E14 [get_ports "${pathPrefix}_dq[19]"]

    # PadFunction: IO_L12N_T1_MRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[20]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[20]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[20]"]
    set_property PACKAGE_PIN G13 [get_ports "${pathPrefix}_dq[20]"]

    # PadFunction: IO_L10P_T1_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[21]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[21]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[21]"]
    set_property PACKAGE_PIN G12 [get_ports "${pathPrefix}_dq[21]"]

    # PadFunction: IO_L11N_T1_SRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[22]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[22]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[22]"]
    set_property PACKAGE_PIN F14 [get_ports "${pathPrefix}_dq[22]"]

    # PadFunction: IO_L12P_T1_MRCC_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[23]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[23]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[23]"]
    set_property PACKAGE_PIN G14 [get_ports "${pathPrefix}_dq[23]"]

    # PadFunction: IO_L2P_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[24]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[24]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[24]"]
    set_property PACKAGE_PIN B14 [get_ports "${pathPrefix}_dq[24]"]

    # PadFunction: IO_L4N_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[25]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[25]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[25]"]
    set_property PACKAGE_PIN C13 [get_ports "${pathPrefix}_dq[25]"]

    # PadFunction: IO_L1N_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[26]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[26]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[26]"]
    set_property PACKAGE_PIN B16 [get_ports "${pathPrefix}_dq[26]"]

    # PadFunction: IO_L5N_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[27]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[27]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[27]"]
    set_property PACKAGE_PIN D15 [get_ports "${pathPrefix}_dq[27]"]

    # PadFunction: IO_L4P_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[28]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[28]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[28]"]
    set_property PACKAGE_PIN D13 [get_ports "${pathPrefix}_dq[28]"]

    # PadFunction: IO_L6P_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[29]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[29]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[29]"]
    set_property PACKAGE_PIN E12 [get_ports "${pathPrefix}_dq[29]"]

    # PadFunction: IO_L1P_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[30]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[30]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[30]"]
    set_property PACKAGE_PIN C16 [get_ports "${pathPrefix}_dq[30]"]

    # PadFunction: IO_L5P_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[31]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[31]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[31]"]
    set_property PACKAGE_PIN D16 [get_ports "${pathPrefix}_dq[31]"]

    # PadFunction: IO_L1P_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[32]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[32]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[32]"]
    set_property PACKAGE_PIN A24 [get_ports "${pathPrefix}_dq[32]"]

    # PadFunction: IO_L4N_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[33]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[33]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[33]"]
    set_property PACKAGE_PIN B23 [get_ports "${pathPrefix}_dq[33]"]

    # PadFunction: IO_L5N_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[34]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[34]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[34]"]
    set_property PACKAGE_PIN B27 [get_ports "${pathPrefix}_dq[34]"]

    # PadFunction: IO_L5P_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[35]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[35]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[35]"]
    set_property PACKAGE_PIN B26 [get_ports "${pathPrefix}_dq[35]"]

    # PadFunction: IO_L2N_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[36]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[36]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[36]"]
    set_property PACKAGE_PIN A22 [get_ports "${pathPrefix}_dq[36]"]

    # PadFunction: IO_L2P_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[37]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[37]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[37]"]
    set_property PACKAGE_PIN B22 [get_ports "${pathPrefix}_dq[37]"]

    # PadFunction: IO_L1N_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[38]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[38]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[38]"]
    set_property PACKAGE_PIN A25 [get_ports "${pathPrefix}_dq[38]"]

    # PadFunction: IO_L6P_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[39]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[39]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[39]"]
    set_property PACKAGE_PIN C24 [get_ports "${pathPrefix}_dq[39]"]

    # PadFunction: IO_L7N_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[40]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[40]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[40]"]
    set_property PACKAGE_PIN E24 [get_ports "${pathPrefix}_dq[40]"]

    # PadFunction: IO_L10N_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[41]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[41]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[41]"]
    set_property PACKAGE_PIN D23 [get_ports "${pathPrefix}_dq[41]"]

    # PadFunction: IO_L11N_T1_SRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[42]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[42]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[42]"]
    set_property PACKAGE_PIN D26 [get_ports "${pathPrefix}_dq[42]"]

    # PadFunction: IO_L12P_T1_MRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[43]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[43]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[43]"]
    set_property PACKAGE_PIN C25 [get_ports "${pathPrefix}_dq[43]"]

    # PadFunction: IO_L7P_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[44]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[44]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[44]"]
    set_property PACKAGE_PIN E23 [get_ports "${pathPrefix}_dq[44]"]

    # PadFunction: IO_L10P_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[45]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[45]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[45]"]
    set_property PACKAGE_PIN D22 [get_ports "${pathPrefix}_dq[45]"]

    # PadFunction: IO_L8P_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[46]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[46]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[46]"]
    set_property PACKAGE_PIN F22 [get_ports "${pathPrefix}_dq[46]"]

    # PadFunction: IO_L8N_T1_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[47]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[47]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[47]"]
    set_property PACKAGE_PIN E22 [get_ports "${pathPrefix}_dq[47]"]

    # PadFunction: IO_L17N_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[48]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[48]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[48]"]
    set_property PACKAGE_PIN A30 [get_ports "${pathPrefix}_dq[48]"]

    # PadFunction: IO_L13P_T2_MRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[49]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[49]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[49]"]
    set_property PACKAGE_PIN D27 [get_ports "${pathPrefix}_dq[49]"]

    # PadFunction: IO_L17P_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[50]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[50]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[50]"]
    set_property PACKAGE_PIN A29 [get_ports "${pathPrefix}_dq[50]"]

    # PadFunction: IO_L14P_T2_SRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[51]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[51]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[51]"]
    set_property PACKAGE_PIN C28 [get_ports "${pathPrefix}_dq[51]"]

    # PadFunction: IO_L13N_T2_MRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[52]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[52]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[52]"]
    set_property PACKAGE_PIN D28 [get_ports "${pathPrefix}_dq[52]"]

    # PadFunction: IO_L18N_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[53]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[53]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[53]"]
    set_property PACKAGE_PIN B31 [get_ports "${pathPrefix}_dq[53]"]

    # PadFunction: IO_L16P_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[54]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[54]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[54]"]
    set_property PACKAGE_PIN A31 [get_ports "${pathPrefix}_dq[54]"]

    # PadFunction: IO_L16N_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[55]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[55]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[55]"]
    set_property PACKAGE_PIN A32 [get_ports "${pathPrefix}_dq[55]"]

    # PadFunction: IO_L19P_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[56]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[56]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[56]"]
    set_property PACKAGE_PIN E30 [get_ports "${pathPrefix}_dq[56]"]

    # PadFunction: IO_L22P_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[57]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[57]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[57]"]
    set_property PACKAGE_PIN F29 [get_ports "${pathPrefix}_dq[57]"]

    # PadFunction: IO_L24P_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[58]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[58]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[58]"]
    set_property PACKAGE_PIN F30 [get_ports "${pathPrefix}_dq[58]"]

    # PadFunction: IO_L23N_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[59]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[59]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[59]"]
    set_property PACKAGE_PIN F27 [get_ports "${pathPrefix}_dq[59]"]

    # PadFunction: IO_L20N_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[60]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[60]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[60]"]
    set_property PACKAGE_PIN C30 [get_ports "${pathPrefix}_dq[60]"]

    # PadFunction: IO_L22N_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[61]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[61]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[61]"]
    set_property PACKAGE_PIN E29 [get_ports "${pathPrefix}_dq[61]"]

    # PadFunction: IO_L23P_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[62]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[62]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[62]"]
    set_property PACKAGE_PIN F26 [get_ports "${pathPrefix}_dq[62]"]

    # PadFunction: IO_L20P_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[63]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[63]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[63]"]
    set_property PACKAGE_PIN D30 [get_ports "${pathPrefix}_dq[63]"]

    # PadFunction: IO_L8N_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[15]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[15]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[15]"]
    set_property PACKAGE_PIN E17 [get_ports "${pathPrefix}_addr[15]"]

    # PadFunction: IO_L8P_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[14]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[14]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[14]"]
    set_property PACKAGE_PIN F17 [get_ports "${pathPrefix}_addr[14]"]

    # PadFunction: IO_L5N_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[13]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[13]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[13]"]
    set_property PACKAGE_PIN A21 [get_ports "${pathPrefix}_addr[13]"]

    # PadFunction: IO_L2N_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[12]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[12]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[12]"]
    set_property PACKAGE_PIN A15 [get_ports "${pathPrefix}_addr[12]"]

    # PadFunction: IO_L4P_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[11]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[11]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[11]"]
    set_property PACKAGE_PIN B17 [get_ports "${pathPrefix}_addr[11]"]

    # PadFunction: IO_L5P_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[10]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[10]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[10]"]
    set_property PACKAGE_PIN B21 [get_ports "${pathPrefix}_addr[10]"]

    # PadFunction: IO_L1P_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[9]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[9]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[9]"]
    set_property PACKAGE_PIN C19 [get_ports "${pathPrefix}_addr[9]"]

    # PadFunction: IO_L10N_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[8]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[8]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[8]"]
    set_property PACKAGE_PIN D17 [get_ports "${pathPrefix}_addr[8]"]

    # PadFunction: IO_L6P_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[7]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[7]"]
    set_property PACKAGE_PIN C18 [get_ports "${pathPrefix}_addr[7]"]

    # PadFunction: IO_L7P_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[6]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[6]"]
    set_property PACKAGE_PIN D20 [get_ports "${pathPrefix}_addr[6]"]

    # PadFunction: IO_L2P_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[5]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[5]"]
    set_property PACKAGE_PIN A16 [get_ports "${pathPrefix}_addr[5]"]

    # PadFunction: IO_L4N_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[4]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[4]"]
    set_property PACKAGE_PIN A17 [get_ports "${pathPrefix}_addr[4]"]

    # PadFunction: IO_L3N_T0_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[3]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[3]"]
    set_property PACKAGE_PIN A19 [get_ports "${pathPrefix}_addr[3]"]

    # PadFunction: IO_L7N_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[2]"]
    set_property PACKAGE_PIN C20 [get_ports "${pathPrefix}_addr[2]"]

    # PadFunction: IO_L1N_T0_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[1]"]
    set_property PACKAGE_PIN B19 [get_ports "${pathPrefix}_addr[1]"]

    # PadFunction: IO_L3P_T0_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[0]"]
    set_property PACKAGE_PIN A20 [get_ports "${pathPrefix}_addr[0]"]

    # PadFunction: IO_L10P_T1_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[2]"]
    set_property PACKAGE_PIN D18 [get_ports "${pathPrefix}_ba[2]"]

    # PadFunction: IO_L9N_T1_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[1]"]
    set_property PACKAGE_PIN C21 [get_ports "${pathPrefix}_ba[1]"]

    # PadFunction: IO_L9P_T1_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[0]"]
    set_property PACKAGE_PIN D21 [get_ports "${pathPrefix}_ba[0]"]

    # PadFunction: IO_L15N_T2_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ras_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ras_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ras_n"]
    set_property PACKAGE_PIN E20 [get_ports "${pathPrefix}_ras_n"]

    # PadFunction: IO_L16P_T2_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cas_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cas_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cas_n"]
    set_property PACKAGE_PIN K17 [get_ports "${pathPrefix}_cas_n"]

    # PadFunction: IO_L15P_T2_DQS_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_we_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_we_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_we_n"]
    set_property PACKAGE_PIN F20 [get_ports "${pathPrefix}_we_n"]

    # PadFunction: IO_L19P_T3_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_reset_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_reset_n"]
    set_property IOSTANDARD LVCMOS15 [get_ports "${pathPrefix}_reset_n"]
    set_property PACKAGE_PIN P18 [get_ports "${pathPrefix}_reset_n"]

    # PadFunction: IO_L14P_T2_SRCC_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cke"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cke"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cke"]
    set_property PACKAGE_PIN K19 [get_ports "${pathPrefix}_cke"]

    # PadFunction: IO_L17N_T2_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_odt"]
    set_property SLEW FAST [get_ports "${pathPrefix}_odt"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_odt"]
    set_property PACKAGE_PIN H20 [get_ports "${pathPrefix}_odt"]

    # PadFunction: IO_L16N_T2_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cs_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cs_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cs_n"]
    set_property PACKAGE_PIN J17 [get_ports "${pathPrefix}_cs_n"]

    # PadFunction: IO_L22N_T3_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[0]"]
    set_property PACKAGE_PIN M13 [get_ports "${pathPrefix}_dm[0]"]

    # PadFunction: IO_L16P_T2_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[1]"]
    set_property PACKAGE_PIN K15 [get_ports "${pathPrefix}_dm[1]"]

    # PadFunction: IO_L10N_T1_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[2]"]
    set_property PACKAGE_PIN F12 [get_ports "${pathPrefix}_dm[2]"]

    # PadFunction: IO_L2N_T0_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[3]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[3]"]
    set_property PACKAGE_PIN A14 [get_ports "${pathPrefix}_dm[3]"]

    # PadFunction: IO_L4P_T0_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[4]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[4]"]
    set_property PACKAGE_PIN C23 [get_ports "${pathPrefix}_dm[4]"]

    # PadFunction: IO_L11P_T1_SRCC_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[5]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[5]"]
    set_property PACKAGE_PIN D25 [get_ports "${pathPrefix}_dm[5]"]

    # PadFunction: IO_L18P_T2_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[6]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[6]"]
    set_property PACKAGE_PIN C31 [get_ports "${pathPrefix}_dm[6]"]

    # PadFunction: IO_L24N_T3_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[7]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[7]"]
    set_property PACKAGE_PIN F31 [get_ports "${pathPrefix}_dm[7]"]

    # PadFunction: IO_L21P_T3_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property PACKAGE_PIN N16 [get_ports "${pathPrefix}_dqs_p[0]"]

    # PadFunction: IO_L21N_T3_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property PACKAGE_PIN M16 [get_ports "${pathPrefix}_dqs_n[0]"]

    # PadFunction: IO_L15P_T2_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property PACKAGE_PIN K12 [get_ports "${pathPrefix}_dqs_p[1]"]

    # PadFunction: IO_L15N_T2_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property PACKAGE_PIN J12 [get_ports "${pathPrefix}_dqs_n[1]"]

    # PadFunction: IO_L9P_T1_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property PACKAGE_PIN H16 [get_ports "${pathPrefix}_dqs_p[2]"]

    # PadFunction: IO_L9N_T1_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property PACKAGE_PIN G16 [get_ports "${pathPrefix}_dqs_n[2]"]

    # PadFunction: IO_L3P_T0_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property PACKAGE_PIN C15 [get_ports "${pathPrefix}_dqs_p[3]"]

    # PadFunction: IO_L3N_T0_DQS_39
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property PACKAGE_PIN C14 [get_ports "${pathPrefix}_dqs_n[3]"]

    # PadFunction: IO_L3P_T0_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property PACKAGE_PIN A26 [get_ports "${pathPrefix}_dqs_p[4]"]

    # PadFunction: IO_L3N_T0_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property PACKAGE_PIN A27 [get_ports "${pathPrefix}_dqs_n[4]"]

    # PadFunction: IO_L9P_T1_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property PACKAGE_PIN F25 [get_ports "${pathPrefix}_dqs_p[5]"]

    # PadFunction: IO_L9N_T1_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property PACKAGE_PIN E25 [get_ports "${pathPrefix}_dqs_n[5]"]

    # PadFunction: IO_L15P_T2_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property PACKAGE_PIN B28 [get_ports "${pathPrefix}_dqs_p[6]"]

    # PadFunction: IO_L15N_T2_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property PACKAGE_PIN B29 [get_ports "${pathPrefix}_dqs_n[6]"]

    # PadFunction: IO_L21P_T3_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property PACKAGE_PIN E27 [get_ports "${pathPrefix}_dqs_p[7]"]

    # PadFunction: IO_L21N_T3_DQS_37
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property PACKAGE_PIN E28 [get_ports "${pathPrefix}_dqs_n[7]"]

    # PadFunction: IO_L12P_T1_MRCC_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ck_p"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ck_p"]
    set_property IOSTANDARD DIFF_SSTL15 [get_ports "${pathPrefix}_ck_p"]
    set_property PACKAGE_PIN E19 [get_ports "${pathPrefix}_ck_p"]

    # PadFunction: IO_L12N_T1_MRCC_38
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ck_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ck_n"]
    set_property IOSTANDARD DIFF_SSTL15 [get_ports "${pathPrefix}_ck_n"]
    set_property PACKAGE_PIN E18 [get_ports "${pathPrefix}_ck_n"]

    set bankPrefix "b0_*"
    if {[getAWBParams {"ddr_sdram_xilinx_v23_config" "DRAM_NUM_BANKS"}] < 2} {
        # Only one bank.  No prefix needed.
        set bankPrefix "*"
    }

    set_property LOC PHASER_OUT_PHY_X1Y31 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y30 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y29 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y28 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y35 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y34 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y33 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y39 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y38 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y37 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out"]
    set_property LOC PHASER_OUT_PHY_X1Y36 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out"]

    set_property LOC PHASER_IN_PHY_X1Y31 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y30 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y29 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y28 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in"]
    ## set_property LOC PHASER_IN_PHY_X1Y35 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in"]
    ## set_property LOC PHASER_IN_PHY_X1Y34 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in"]
    ## set_property LOC PHASER_IN_PHY_X1Y33 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y39 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y38 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y37 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in"]
    set_property LOC PHASER_IN_PHY_X1Y36 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in"]


    set_property LOC OUT_FIFO_X1Y31 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo"]
    set_property LOC OUT_FIFO_X1Y30 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo"]
    set_property LOC OUT_FIFO_X1Y29 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo"]
    set_property LOC OUT_FIFO_X1Y28 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo"]
    set_property LOC OUT_FIFO_X1Y35 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo"]
    set_property LOC OUT_FIFO_X1Y34 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo"]
    set_property LOC OUT_FIFO_X1Y33 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo"]
    set_property LOC OUT_FIFO_X1Y39 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo"]
    set_property LOC OUT_FIFO_X1Y38 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo"]
    set_property LOC OUT_FIFO_X1Y37 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo"]
    set_property LOC OUT_FIFO_X1Y36 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo"]

    set_property LOC IN_FIFO_X1Y31 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y30 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y29 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y28 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y39 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y38 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y37 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo"]
    set_property LOC IN_FIFO_X1Y36 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo"]

    set_property LOC PHY_CONTROL_X1Y7 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i"]
    set_property LOC PHY_CONTROL_X1Y8 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i"]
    set_property LOC PHY_CONTROL_X1Y9 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i"]

    set_property LOC PHASER_REF_X1Y7 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i"]
    set_property LOC PHASER_REF_X1Y8 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i"]
    set_property LOC PHASER_REF_X1Y9 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i"]

    set_property LOC OLOGIC_X1Y393 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y381 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y369 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y357 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y493 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y481 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y469 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts"]
    set_property LOC OLOGIC_X1Y457 [get_cells  -hier -filter "NAME =~ */${bankPrefix}/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts"]

    set_property LOC PLLE2_ADV_X1Y8 [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_infrastructure/plle2_i"]
    set_property LOC MMCME2_ADV_X1Y8 [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_infrastructure/gen_mmcm.mmcm_i"]

    # These 4 are guesses based on the VC707
#    set_property LOC MMCME2_ADV_X0Y6 [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_v2_3/u_iodelay_ctrl/clk_ref_mmcm_gen.mmcm_i"]
#    set_property LOC BUFGCTRL_X0Y8   [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_v2_3/u_iodelay_ctrl/clk_ref_300_400_en.clk_ref_400.u_bufg_clk_ref_400"]
#    set_property LOC BUFGCTRL_X0Y19   [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_v2_3/u_ddr3_infrastructure/u_bufg_clkdiv0"]
#    set_property LOC BUFGCTRL_X0Y21   [get_cells -hier -filter "NAME =~ */${bankPrefix}/u_ddr3_v2_3/u_ddr3_infrastructure/gen_mmcm.u_bufg_mmcm_ps_clk"]
}


proc annotateDDRWires1 { pathPrefix } { 
    if {[getAWBParams {"ddr_sdram_xilinx_v23_config" "DRAM_NUM_BANKS"}] < 2} {
        # Only one bank.
        return
    }

    # PadFunction: IO_L7N_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[0]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[0]"]
    set_property PACKAGE_PIN AN24 [get_ports "${pathPrefix}_dq[0]"]

    # PadFunction: IO_L7P_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[1]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[1]"]
    set_property PACKAGE_PIN AM24 [get_ports "${pathPrefix}_dq[1]"]

    # PadFunction: IO_L11N_T1_SRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[2]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[2]"]
    set_property PACKAGE_PIN AR22 [get_ports "${pathPrefix}_dq[2]"]

    # PadFunction: IO_L11P_T1_SRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[3]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[3]"]
    set_property PACKAGE_PIN AR23 [get_ports "${pathPrefix}_dq[3]"]

    # PadFunction: IO_L8N_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[4]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[4]"]
    set_property PACKAGE_PIN AN23 [get_ports "${pathPrefix}_dq[4]"]

    # PadFunction: IO_L8P_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[5]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[5]"]
    set_property PACKAGE_PIN AM23 [get_ports "${pathPrefix}_dq[5]"]

    # PadFunction: IO_L10P_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[6]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[6]"]
    set_property PACKAGE_PIN AN21 [get_ports "${pathPrefix}_dq[6]"]

    # PadFunction: IO_L10N_T1_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[7]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[7]"]
    set_property PACKAGE_PIN AP21 [get_ports "${pathPrefix}_dq[7]"]

    # PadFunction: IO_L1N_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[8]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[8]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[8]"]
    set_property PACKAGE_PIN AK23 [get_ports "${pathPrefix}_dq[8]"]

    # PadFunction: IO_L1P_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[9]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[9]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[9]"]
    set_property PACKAGE_PIN AJ23 [get_ports "${pathPrefix}_dq[9]"]

    # PadFunction: IO_L4P_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[10]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[10]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[10]"]
    set_property PACKAGE_PIN AL21 [get_ports "${pathPrefix}_dq[10]"]

    # PadFunction: IO_L4N_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[11]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[11]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[11]"]
    set_property PACKAGE_PIN AM21 [get_ports "${pathPrefix}_dq[11]"]

    # PadFunction: IO_L5P_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[12]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[12]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[12]"]
    set_property PACKAGE_PIN AJ21 [get_ports "${pathPrefix}_dq[12]"]

    # PadFunction: IO_L5N_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[13]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[13]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[13]"]
    set_property PACKAGE_PIN AJ20 [get_ports "${pathPrefix}_dq[13]"]

    # PadFunction: IO_L2P_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[14]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[14]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[14]"]
    set_property PACKAGE_PIN AK20 [get_ports "${pathPrefix}_dq[14]"]

    # PadFunction: IO_L2N_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[15]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[15]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[15]"]
    set_property PACKAGE_PIN AL20 [get_ports "${pathPrefix}_dq[15]"]

    # PadFunction: IO_L14N_T2_SRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[16]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[16]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[16]"]
    set_property PACKAGE_PIN AW22 [get_ports "${pathPrefix}_dq[16]"]

    # PadFunction: IO_L14P_T2_SRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[17]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[17]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[17]"]
    set_property PACKAGE_PIN AW23 [get_ports "${pathPrefix}_dq[17]"]

    # PadFunction: IO_L17N_T2_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[18]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[18]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[18]"]
    set_property PACKAGE_PIN AW21 [get_ports "${pathPrefix}_dq[18]"]

    # PadFunction: IO_L17P_T2_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[19]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[19]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[19]"]
    set_property PACKAGE_PIN AV21 [get_ports "${pathPrefix}_dq[19]"]

    # PadFunction: IO_L13P_T2_MRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[20]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[20]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[20]"]
    set_property PACKAGE_PIN AU23 [get_ports "${pathPrefix}_dq[20]"]

    # PadFunction: IO_L13N_T2_MRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[21]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[21]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[21]"]
    set_property PACKAGE_PIN AV23 [get_ports "${pathPrefix}_dq[21]"]

    # PadFunction: IO_L16P_T2_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[22]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[22]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[22]"]
    set_property PACKAGE_PIN AR24 [get_ports "${pathPrefix}_dq[22]"]

    # PadFunction: IO_L16N_T2_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[23]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[23]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[23]"]
    set_property PACKAGE_PIN AT24 [get_ports "${pathPrefix}_dq[23]"]

    # PadFunction: IO_L24P_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[24]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[24]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[24]"]
    set_property PACKAGE_PIN BB24 [get_ports "${pathPrefix}_dq[24]"]

    # PadFunction: IO_L22N_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[25]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[25]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[25]"]
    set_property PACKAGE_PIN BA24 [get_ports "${pathPrefix}_dq[25]"]

    # PadFunction: IO_L19P_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[26]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[26]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[26]"]
    set_property PACKAGE_PIN AY23 [get_ports "${pathPrefix}_dq[26]"]

    # PadFunction: IO_L22P_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[27]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[27]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[27]"]
    set_property PACKAGE_PIN AY24 [get_ports "${pathPrefix}_dq[27]"]

    # PadFunction: IO_L20P_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[28]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[28]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[28]"]
    set_property PACKAGE_PIN AY25 [get_ports "${pathPrefix}_dq[28]"]

    # PadFunction: IO_L20N_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[29]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[29]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[29]"]
    set_property PACKAGE_PIN BA25 [get_ports "${pathPrefix}_dq[29]"]

    # PadFunction: IO_L23N_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[30]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[30]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[30]"]
    set_property PACKAGE_PIN BB21 [get_ports "${pathPrefix}_dq[30]"]

    # PadFunction: IO_L23P_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[31]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[31]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[31]"]
    set_property PACKAGE_PIN BA21 [get_ports "${pathPrefix}_dq[31]"]

    # PadFunction: IO_L22P_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[32]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[32]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[32]"]
    set_property PACKAGE_PIN AY14 [get_ports "${pathPrefix}_dq[32]"]

    # PadFunction: IO_L19P_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[33]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[33]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[33]"]
    set_property PACKAGE_PIN AW15 [get_ports "${pathPrefix}_dq[33]"]

    # PadFunction: IO_L23P_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[34]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[34]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[34]"]
    set_property PACKAGE_PIN BB14 [get_ports "${pathPrefix}_dq[34]"]

    # PadFunction: IO_L23N_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[35]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[35]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[35]"]
    set_property PACKAGE_PIN BB13 [get_ports "${pathPrefix}_dq[35]"]

    # PadFunction: IO_L20P_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[36]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[36]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[36]"]
    set_property PACKAGE_PIN AW12 [get_ports "${pathPrefix}_dq[36]"]

    # PadFunction: IO_L22N_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[37]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[37]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[37]"]
    set_property PACKAGE_PIN AY13 [get_ports "${pathPrefix}_dq[37]"]

    # PadFunction: IO_L20N_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[38]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[38]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[38]"]
    set_property PACKAGE_PIN AY12 [get_ports "${pathPrefix}_dq[38]"]

    # PadFunction: IO_L24P_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[39]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[39]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[39]"]
    set_property PACKAGE_PIN BA12 [get_ports "${pathPrefix}_dq[39]"]

    # PadFunction: IO_L17N_T2_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[40]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[40]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[40]"]
    set_property PACKAGE_PIN AU12 [get_ports "${pathPrefix}_dq[40]"]

    # PadFunction: IO_L13N_T2_MRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[41]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[41]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[41]"]
    set_property PACKAGE_PIN AU13 [get_ports "${pathPrefix}_dq[41]"]

    # PadFunction: IO_L17P_T2_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[42]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[42]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[42]"]
    set_property PACKAGE_PIN AT12 [get_ports "${pathPrefix}_dq[42]"]

    # PadFunction: IO_L13P_T2_MRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[43]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[43]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[43]"]
    set_property PACKAGE_PIN AU14 [get_ports "${pathPrefix}_dq[43]"]

    # PadFunction: IO_L14P_T2_SRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[44]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[44]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[44]"]
    set_property PACKAGE_PIN AV13 [get_ports "${pathPrefix}_dq[44]"]

    # PadFunction: IO_L14N_T2_SRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[45]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[45]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[45]"]
    set_property PACKAGE_PIN AW13 [get_ports "${pathPrefix}_dq[45]"]

    # PadFunction: IO_L16N_T2_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[46]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[46]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[46]"]
    set_property PACKAGE_PIN AT15 [get_ports "${pathPrefix}_dq[46]"]

    # PadFunction: IO_L16P_T2_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[47]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[47]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[47]"]
    set_property PACKAGE_PIN AR15 [get_ports "${pathPrefix}_dq[47]"]

    # PadFunction: IO_L5N_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[48]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[48]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[48]"]
    set_property PACKAGE_PIN AL15 [get_ports "${pathPrefix}_dq[48]"]

    # PadFunction: IO_L1N_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[49]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[49]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[49]"]
    set_property PACKAGE_PIN AJ15 [get_ports "${pathPrefix}_dq[49]"]

    # PadFunction: IO_L2P_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[50]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[50]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[50]"]
    set_property PACKAGE_PIN AK14 [get_ports "${pathPrefix}_dq[50]"]

    # PadFunction: IO_L4N_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[51]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[51]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[51]"]
    set_property PACKAGE_PIN AJ12 [get_ports "${pathPrefix}_dq[51]"]

    # PadFunction: IO_L1P_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[52]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[52]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[52]"]
    set_property PACKAGE_PIN AJ16 [get_ports "${pathPrefix}_dq[52]"]

    # PadFunction: IO_L5P_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[53]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[53]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[53]"]
    set_property PACKAGE_PIN AL16 [get_ports "${pathPrefix}_dq[53]"]

    # PadFunction: IO_L4P_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[54]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[54]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[54]"]
    set_property PACKAGE_PIN AJ13 [get_ports "${pathPrefix}_dq[54]"]

    # PadFunction: IO_L2N_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[55]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[55]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[55]"]
    set_property PACKAGE_PIN AK13 [get_ports "${pathPrefix}_dq[55]"]

    # PadFunction: IO_L11P_T1_SRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[56]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[56]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[56]"]
    set_property PACKAGE_PIN AR14 [get_ports "${pathPrefix}_dq[56]"]

    # PadFunction: IO_L11N_T1_SRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[57]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[57]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[57]"]
    set_property PACKAGE_PIN AT14 [get_ports "${pathPrefix}_dq[57]"]

    # PadFunction: IO_L8P_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[58]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[58]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[58]"]
    set_property PACKAGE_PIN AM12 [get_ports "${pathPrefix}_dq[58]"]

    # PadFunction: IO_L10N_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[59]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[59]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[59]"]
    set_property PACKAGE_PIN AP11 [get_ports "${pathPrefix}_dq[59]"]

    # PadFunction: IO_L7P_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[60]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[60]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[60]"]
    set_property PACKAGE_PIN AM13 [get_ports "${pathPrefix}_dq[60]"]

    # PadFunction: IO_L7N_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[61]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[61]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[61]"]
    set_property PACKAGE_PIN AN13 [get_ports "${pathPrefix}_dq[61]"]

    # PadFunction: IO_L8N_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[62]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[62]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[62]"]
    set_property PACKAGE_PIN AM11 [get_ports "${pathPrefix}_dq[62]"]

    # PadFunction: IO_L10P_T1_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dq[63]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dq[63]"]
    set_property IOSTANDARD SSTL15_T_DCI [get_ports "${pathPrefix}_dq[63]"]
    set_property PACKAGE_PIN AN11 [get_ports "${pathPrefix}_dq[63]"]

    # PadFunction: IO_L1P_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[15]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[15]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[15]"]
    set_property PACKAGE_PIN AL19 [get_ports "${pathPrefix}_addr[15]"]

    # PadFunction: IO_L1N_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[14]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[14]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[14]"]
    set_property PACKAGE_PIN AM19 [get_ports "${pathPrefix}_addr[14]"]

    # PadFunction: IO_L2P_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[13]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[13]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[13]"]
    set_property PACKAGE_PIN AK17 [get_ports "${pathPrefix}_addr[13]"]

    # PadFunction: IO_L2N_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[12]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[12]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[12]"]
    set_property PACKAGE_PIN AL17 [get_ports "${pathPrefix}_addr[12]"]

    # PadFunction: IO_L3P_T0_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[11]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[11]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[11]"]
    set_property PACKAGE_PIN AM18 [get_ports "${pathPrefix}_addr[11]"]

    # PadFunction: IO_L3N_T0_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[10]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[10]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[10]"]
    set_property PACKAGE_PIN AM17 [get_ports "${pathPrefix}_addr[10]"]

    # PadFunction: IO_L4P_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[9]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[9]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[9]"]
    set_property PACKAGE_PIN AK19 [get_ports "${pathPrefix}_addr[9]"]

    # PadFunction: IO_L4N_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[8]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[8]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[8]"]
    set_property PACKAGE_PIN AK18 [get_ports "${pathPrefix}_addr[8]"]

    # PadFunction: IO_L5P_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[7]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[7]"]
    set_property PACKAGE_PIN AM16 [get_ports "${pathPrefix}_addr[7]"]

    # PadFunction: IO_L5N_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[6]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[6]"]
    set_property PACKAGE_PIN AN16 [get_ports "${pathPrefix}_addr[6]"]

    # PadFunction: IO_L6P_T0_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[5]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[5]"]
    set_property PACKAGE_PIN AJ18 [get_ports "${pathPrefix}_addr[5]"]

    # PadFunction: IO_L7P_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[4]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[4]"]
    set_property PACKAGE_PIN AP18 [get_ports "${pathPrefix}_addr[4]"]

    # PadFunction: IO_L7N_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[3]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[3]"]
    set_property PACKAGE_PIN AP17 [get_ports "${pathPrefix}_addr[3]"]

    # PadFunction: IO_L8P_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[2]"]
    set_property PACKAGE_PIN AP20 [get_ports "${pathPrefix}_addr[2]"]

    # PadFunction: IO_L8N_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[1]"]
    set_property PACKAGE_PIN AR19 [get_ports "${pathPrefix}_addr[1]"]

    # PadFunction: IO_L9P_T1_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_addr[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_addr[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_addr[0]"]
    set_property PACKAGE_PIN AN19 [get_ports "${pathPrefix}_addr[0]"]

    # PadFunction: IO_L9N_T1_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[2]"]
    set_property PACKAGE_PIN AN18 [get_ports "${pathPrefix}_ba[2]"]

    # PadFunction: IO_L10P_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[1]"]
    set_property PACKAGE_PIN AR18 [get_ports "${pathPrefix}_ba[1]"]

    # PadFunction: IO_L10N_T1_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ba[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ba[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ba[0]"]
    set_property PACKAGE_PIN AR17 [get_ports "${pathPrefix}_ba[0]"]

    # PadFunction: IO_L15N_T2_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ras_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ras_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_ras_n"]
    set_property PACKAGE_PIN AV19 [get_ports "${pathPrefix}_ras_n"]

    # PadFunction: IO_L16P_T2_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cas_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cas_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cas_n"]
    set_property PACKAGE_PIN AT20 [get_ports "${pathPrefix}_cas_n"]

    # PadFunction: IO_L15P_T2_DQS_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_we_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_we_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_we_n"]
    set_property PACKAGE_PIN AU19 [get_ports "${pathPrefix}_we_n"]

    # PadFunction: IO_L19P_T3_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_reset_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_reset_n"]
    set_property IOSTANDARD LVCMOS15 [get_ports "${pathPrefix}_reset_n"]
    set_property PACKAGE_PIN BB19 [get_ports "${pathPrefix}_reset_n"]

    # PadFunction: IO_L14N_T2_SRCC_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cke"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cke"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cke"]
    set_property PACKAGE_PIN AW17 [get_ports "${pathPrefix}_cke"]

    # PadFunction: IO_L18P_T2_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_odt"]
    set_property SLEW FAST [get_ports "${pathPrefix}_odt"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_odt"]
    set_property PACKAGE_PIN AT16 [get_ports "${pathPrefix}_odt"]

    # PadFunction: IO_L17P_T2_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_cs_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_cs_n"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_cs_n"]
    set_property PACKAGE_PIN AV16 [get_ports "${pathPrefix}_cs_n"]

    # PadFunction: IO_L12P_T1_MRCC_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[0]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[0]"]
    set_property PACKAGE_PIN AT22 [get_ports "${pathPrefix}_dm[0]"]

    # PadFunction: IO_L6P_T0_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[1]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[1]"]
    set_property PACKAGE_PIN AL22 [get_ports "${pathPrefix}_dm[1]"]

    # PadFunction: IO_L18P_T2_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[2]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[2]"]
    set_property PACKAGE_PIN AU24 [get_ports "${pathPrefix}_dm[2]"]

    # PadFunction: IO_L24N_T3_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[3]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[3]"]
    set_property PACKAGE_PIN BB23 [get_ports "${pathPrefix}_dm[3]"]

    # PadFunction: IO_L24N_T3_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[4]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[4]"]
    set_property PACKAGE_PIN BB12 [get_ports "${pathPrefix}_dm[4]"]

    # PadFunction: IO_L18P_T2_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[5]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[5]"]
    set_property PACKAGE_PIN AV15 [get_ports "${pathPrefix}_dm[5]"]

    # PadFunction: IO_L6P_T0_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[6]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[6]"]
    set_property PACKAGE_PIN AK12 [get_ports "${pathPrefix}_dm[6]"]

    # PadFunction: IO_L12P_T1_MRCC_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dm[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dm[7]"]
    set_property IOSTANDARD SSTL15 [get_ports "${pathPrefix}_dm[7]"]
    set_property PACKAGE_PIN AP13 [get_ports "${pathPrefix}_dm[7]"]

    # PadFunction: IO_L9P_T1_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[0]"]
    set_property PACKAGE_PIN AP23 [get_ports "${pathPrefix}_dqs_p[0]"]

    # PadFunction: IO_L9N_T1_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[0]"]
    set_property PACKAGE_PIN AP22 [get_ports "${pathPrefix}_dqs_n[0]"]

    # PadFunction: IO_L3P_T0_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[1]"]
    set_property PACKAGE_PIN AJ22 [get_ports "${pathPrefix}_dqs_p[1]"]

    # PadFunction: IO_L3N_T0_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[1]"]
    set_property PACKAGE_PIN AK22 [get_ports "${pathPrefix}_dqs_n[1]"]

    # PadFunction: IO_L15P_T2_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[2]"]
    set_property PACKAGE_PIN AT21 [get_ports "${pathPrefix}_dqs_p[2]"]

    # PadFunction: IO_L15N_T2_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[2]"]
    set_property PACKAGE_PIN AU21 [get_ports "${pathPrefix}_dqs_n[2]"]

    # PadFunction: IO_L21P_T3_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[3]"]
    set_property PACKAGE_PIN BA22 [get_ports "${pathPrefix}_dqs_p[3]"]

    # PadFunction: IO_L21N_T3_DQS_33 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[3]"]
    set_property PACKAGE_PIN BB22 [get_ports "${pathPrefix}_dqs_n[3]"]

    # PadFunction: IO_L21P_T3_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[4]"]
    set_property PACKAGE_PIN BA15 [get_ports "${pathPrefix}_dqs_p[4]"]

    # PadFunction: IO_L21N_T3_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[4]"]
    set_property PACKAGE_PIN BA14 [get_ports "${pathPrefix}_dqs_n[4]"]

    # PadFunction: IO_L15P_T2_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[5]"]
    set_property PACKAGE_PIN AP12 [get_ports "${pathPrefix}_dqs_p[5]"]

    # PadFunction: IO_L15N_T2_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[5]"]
    set_property PACKAGE_PIN AR12 [get_ports "${pathPrefix}_dqs_n[5]"]

    # PadFunction: IO_L3P_T0_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[6]"]
    set_property PACKAGE_PIN AK15 [get_ports "${pathPrefix}_dqs_p[6]"]

    # PadFunction: IO_L3N_T0_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[6]"]
    set_property PACKAGE_PIN AL14 [get_ports "${pathPrefix}_dqs_n[6]"]

    # PadFunction: IO_L9P_T1_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_p[7]"]
    set_property PACKAGE_PIN AN15 [get_ports "${pathPrefix}_dqs_p[7]"]

    # PadFunction: IO_L9N_T1_DQS_31 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property SLEW FAST [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports "${pathPrefix}_dqs_n[7]"]
    set_property PACKAGE_PIN AN14 [get_ports "${pathPrefix}_dqs_n[7]"]

    # PadFunction: IO_L12P_T1_MRCC_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ck_p"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ck_p"]
    set_property IOSTANDARD DIFF_SSTL15 [get_ports "${pathPrefix}_ck_p"]
    set_property PACKAGE_PIN AT17 [get_ports "${pathPrefix}_ck_p"]

    # PadFunction: IO_L12N_T1_MRCC_32 
    set_property VCCAUX_IO HIGH [get_ports "${pathPrefix}_ck_n"]
    set_property SLEW FAST [get_ports "${pathPrefix}_ck_n"]
    set_property IOSTANDARD DIFF_SSTL15 [get_ports "${pathPrefix}_ck_n"]
    set_property PACKAGE_PIN AU17 [get_ports "${pathPrefix}_ck_n"]



    set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
    set_property LOC PHASER_OUT_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]

    set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
    ## set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
    ## set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
    ## set_property LOC PHASER_IN_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
    set_property LOC PHASER_IN_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]


    set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
    set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
    set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
    set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
    set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
    set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
    set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
    set_property LOC OUT_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
    set_property LOC OUT_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
    set_property LOC OUT_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
    set_property LOC OUT_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]

    set_property LOC IN_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
    set_property LOC IN_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]

    set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
    set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
    set_property LOC PHY_CONTROL_X1Y3 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]

    set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
    set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
    set_property LOC PHASER_REF_X1Y3 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]

    set_property LOC OLOGIC_X1Y93 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y69 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y193 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y181 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y169 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
    set_property LOC OLOGIC_X1Y157 [get_cells  -hier -filter {NAME =~ */b1_*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]

    set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */b1_*/u_ddr3_infrastructure/plle2_i}]
    set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */b1_*/u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
}
    

proc ddr3PARConstraints { } {
    set pathPrefix ""

    global IS_AREA_GROUP_BUILD
    global IS_TOP_BUILD

    if {$IS_TOP_BUILD} {
        annotateDDRWires0 "ddrWires_bank_wires_0"
        annotateDDRWires1 "ddrWires_bank_wires_1"
    } else {
        annotateDDRWires0 "wires_0"
        annotateDDRWires1 "wires_1"
    }


    ##
    ## Timing
    ##

    set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r*}] \
                        -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                        -setup 6

    set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r*}] \
                        -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                        -hold 5

    #set_max_delay -from [get_cells -hier -filter {NAME =~ */u_phase_detector && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *pos_edge_samp*}] 1.250000
    #set_max_delay -from [get_cells -hier -filter {NAME =~ */u_phase_detector && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *neg_edge_samp*}] 1.250000
              
    set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

    set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
    set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start

    set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
    set_max_delay -from [get_cells -hier rstdiv0_sync_r1*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
              
    set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
    #set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/*rst_r1*}] 20


    # Declare clocks for area group builds. 
    if {$IS_AREA_GROUP_BUILD} {
        create_clock -name ddrWires_rawClock  -period 5.000 [get_ports CLK_rawClock]
    }


    ###########################################################################
    ##  Area constraints
    ###########################################################################

    if {[getAWBParams {"area_group_tool" "AREA_GROUPS_PAR_DEVICE_AG"}] != "1"} {
        startgroup
        create_pblock pblock_ddr3_0
        resize_pblock pblock_ddr3_0 -add {SLICE_X132Y344:SLICE_X169Y449}
        add_cells_to_pblock pblock_ddr3_0 [get_cells -hier -filter {NAME =~ m_sys_sys_vp_m_mod/llpi_phys_plat_sdram_b_ddrSynth/*}]
        endgroup

        if {[getAWBParams {"ddr_sdram_xilinx_v23_config" "DRAM_NUM_BANKS"}] > 1} {
            startgroup
            create_pblock pblock_ddr3_1
            resize_pblock pblock_ddr3_1 -add {SLICE_X132Y50:SLICE_X169Y155}
            add_cells_to_pblock pblock_ddr3_1 [get_cells -hier -filter {NAME =~ m_sys_sys_vp_m_mod/llpi_phys_plat_sdram_b_1_ddrSynth/*}]
            endgroup
        }
    }
}

#Actually apply the constraints.
executePARConstraints ddr3PARConstraints ddr3
