////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2008 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 10.1.03
//  \   \         Application : xaw2verilog
//  /   /         Filename : pll_50_125_200.v
// /___/   /\     Timestamp : 02/17/2009 16:12:30
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -st /home/aparasha/scratch/ise/pll_50_125_200.xaw /home/aparasha/scratch/ise/pll_50_125_200
//Design Name: pll_50_125_200
//Device: xc5vlx110t-1ff1136
//
// Module pll_50_125_200
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.160 ns
// For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.147 ns
`timescale 1ns / 1ps

module pll_50_to_125_200(CLKIN1_IN, 
                      RST_IN, 
                      CLKOUT0_OUT, 
                      CLKOUT1_OUT, 
                      LOCKED_OUT);

    input CLKIN1_IN;
    input RST_IN;
   output CLKOUT0_OUT;
   output CLKOUT1_OUT;
   output LOCKED_OUT;
   
   //wire CLKFBOUT_CLKFBIN;
   wire   CLKFBOUT;
   wire   CLKFBIN;
   
   //wire CLKIN1_IBUFG;
   wire CLKOUT0_BUF;
   wire CLKOUT1_BUF;
   wire GND_BIT;
   wire [4:0] GND_BUS_5;
   wire [15:0] GND_BUS_16;
   wire VCC_BIT;
   
   assign GND_BIT = 0;
   assign GND_BUS_5 = 5'b00000;
   assign GND_BUS_16 = 16'b0000000000000000;
   assign VCC_BIT = 1;
   //IBUFG CLKIN1_IBUFG_INST (.I(CLKIN1_IN), 
   //                         .O(CLKIN1_IBUFG));
   BUFG CLKOUT0_BUFG_INST (.I(CLKOUT0_BUF), 
                           .O(CLKOUT0_OUT));
   BUFG CLKOUT1_BUFG_INST (.I(CLKOUT1_BUF), 
                           .O(CLKOUT1_OUT));
   BUFG CLKFB_BUFG_INST (.I(CLKFBOUT),
                         .O(CLKFBIN));

   PLL_ADV PLL_ADV_INST (//.CLKFBIN(CLKFBOUT_CLKFBIN),
                         .CLKFBIN(CLKFBIN),
                         .CLKINSEL(VCC_BIT), 
                         //.CLKIN1(CLKIN1_IBUFG), 
                         .CLKIN1(CLKIN1_IN), 
                         .CLKIN2(GND_BIT), 
                         .DADDR(GND_BUS_5[4:0]), 
                         .DCLK(GND_BIT), 
                         .DEN(GND_BIT), 
                         .DI(GND_BUS_16[15:0]), 
                         .DWE(GND_BIT), 
                         .REL(GND_BIT), 
                         .RST(RST_IN), 
                         .CLKFBDCM(), 
                         //.CLKFBOUT(CLKFBOUT_CLKFBIN), 
                         .CLKFBOUT(CLKFBOUT), 
                         .CLKOUTDCM0(), 
                         .CLKOUTDCM1(), 
                         .CLKOUTDCM2(), 
                         .CLKOUTDCM3(), 
                         .CLKOUTDCM4(), 
                         .CLKOUTDCM5(), 
                         .CLKOUT0(CLKOUT0_BUF), 
                         //.CLKOUT0(CLKOUT0_OUT), 
                         .CLKOUT1(CLKOUT1_BUF), 
                         //.CLKOUT1(CLKOUT1_OUT), 
                         .CLKOUT2(), 
                         .CLKOUT3(), 
                         .CLKOUT4(), 
                         .CLKOUT5(), 
                         .DO(), 
                         .DRDY(), 
                         .LOCKED(LOCKED_OUT));
   defparam PLL_ADV_INST.BANDWIDTH = "OPTIMIZED";
   defparam PLL_ADV_INST.CLKIN1_PERIOD = 20.000;
   defparam PLL_ADV_INST.CLKIN2_PERIOD = 10.000;
   defparam PLL_ADV_INST.CLKOUT0_DIVIDE = 8;
   defparam PLL_ADV_INST.CLKOUT1_DIVIDE = 5;
   defparam PLL_ADV_INST.CLKOUT0_PHASE = 0.000;
   defparam PLL_ADV_INST.CLKOUT1_PHASE = 0.000;
   defparam PLL_ADV_INST.CLKOUT0_DUTY_CYCLE = 0.500;
   defparam PLL_ADV_INST.CLKOUT1_DUTY_CYCLE = 0.500;
   defparam PLL_ADV_INST.COMPENSATION = "SYSTEM_SYNCHRONOUS";
   defparam PLL_ADV_INST.DIVCLK_DIVIDE = 1;
   defparam PLL_ADV_INST.CLKFBOUT_MULT = 20;
   defparam PLL_ADV_INST.CLKFBOUT_PHASE = 0.0;
   defparam PLL_ADV_INST.REF_JITTER = 0.005000;
endmodule

//
// Bluespec interface
//
module mkPLL_50_to_125_200(CLK,
                           RST_N,
                           CLK_125_OUT,
                           CLK_200_OUT,
                           RST_N_OUT);

   input CLK;
   input RST_N;

   output CLK_125_OUT;
   output CLK_200_OUT;
   output RST_N_OUT;
   
   wire   RST;
   
   assign RST = !RST_N;

   pll_50_to_125_200 x (.CLKIN1_IN(CLK),
         .RST_IN(RST),
         .CLKOUT0_OUT(CLK_125_OUT),
         .CLKOUT1_OUT(CLK_200_OUT),
         .LOCKED_OUT(RST_N_OUT));

endmodule
